### ISSUE TITLE
New content in a tarball modified via appending does now show up in RCDS on subsequent submissions

### ISSUE THREAD

**Issue by kherner** [fermitools/jobsub_lite#426] opened 2023-05-26 17:49 UTC
This week I submitted a job via the usual `jobsub_submit -G dune --tar_file_name dropbox:///path/to/my.tar.gz` ... and it failed because I forgot to include a necessary file in my.tar.gz. Simple enough to fix, right? `gunzip /path/to/my.tar.gz; tar uvf /path/to/my.tar my_missing.file; gzip /path/to/my.tar`. I then ran the exact same submission, but in the next job,  my_missing.file was still not found. When I looked at the contents of the unwound tarball in the RCDS repo on a dunegpvm, sure enough the file was not there. I ran `tar tzf /path/to/my.tar.gz`, any my_missing.file was indeed where I expected it. As another test, I deleted /path/to/my.tar.gz and remade it, this time including my_missing.file from the get-go, and did yet another submission. That one worked as expected. So it seems that if you modify the tarball by appending to it that somehow it's not picking up on the fact that the content has changed. Should be very easy to reproduce:

Make my_simple_script.sh that simply does `ls $INPUT_TAR_DIR_LOCAL`

Do `jobsub_submit --tar_file_name whatever.tar.gz <whatever else> file://my_simple_script.sh`

After the submission is done, append another file to whatever.tar.gz. Then repeat the same submission and see if the contents of $INPUT_TAR_DIR_LOCAL change as expected.

**Comment by marcmengel** [comment] 2023-06-06 16:43
Well... not so easy to reproduce... 
```
tar czvf foo.tar.gz tsi.dag tsi2.dag
jobsub_submit -G fermilab --tar_file_name dropbox://foo.tar.gz file://lookaround.sh
gunzip foo.tar.gz
tar uvf foo.tar tsi3.dag
gzip foo.tar
jobsub_submit -G fermilab --tar_file_name dropbox://foo.tar.gz file://lookaround.sh
```
And I get in the first job 
https://landscape.fnal.gov/lens/view/job/1194467.0@jobsub05.fnal.gov/file/lookaround.sh2023_06_06_113028da93d73a-927e-4a21-a886-e395e8ef7d96cluster.1194467.0.out
`INPUT_TAR_DIR_LOCAL=/cvmfs/fifeuser3.opensciencegrid.org/sw/fermilab/f957e5ae3fb58f9f4d0b1b540e934e433c8280ee006051630b621ccb2c57595c`
And in the second:
https://landscape.fnal.gov/lens/view/job/1194476.0@jobsub05.fnal.gov/file/lookaround.sh2023_06_06_113212e77459cc-0bbb-485f-bf34-4bf621b96536cluster.1194476.0.out
`INPUT_TAR_DIR_LOCAL=/cvmfs/fifeuser3.opensciencegrid.org/sw/fermilab/7441c3183613e3b7dbd22afcb67126bbc98a1d9e38738cd1ca61fb6b3fcd7d39`

```
$ ls /cvmfs/fifeuser3.opensciencegrid.org/sw/fermilab/f957e5ae3fb58f9f4d0b1b540e934e433c8280ee006051630b621ccb2c57595c
tsi2.dag  tsi.dag
$ ls /cvmfs/fifeuser3.opensciencegrid.org/sw/fermilab/7441c3183613e3b7dbd22afcb67126bbc98a1d9e38738cd1ca61fb6b3fcd7d39
tsi2.dag  tsi3.dag  tsi.dag
```

So... tell me more about this tarfile you created and updated... Do you still have it, or can you tell me specifically what directory you tarred up and what file you added?

**Comment by marcmengel** [comment] 2023-07-14 15:10
Okay, so I've been attempting to reproduce this, and am still unable to.   
Here is my current setup:
A script:
```
#!/bin/sh

d=/tmp/test_$$
mkdir $d
cd $d

mkdir a
echo > a/f1
echo > a/f2
echo > a/f3

tar czf a.tar.gz a

jobsub_submit -G fermilab --tar-file-name dropbox:a.tar.gz file:///$HOME/lookaround.sh \$INPUT_TAR_DIR_LOCAL/a/f4

gunzip a.tar.gz

echo > a/f4

tar uf a.tar a/f4
gzip a.tar

jobsub_submit -G fermilab --tar-file-name dropbox:a.tar.gz file:///$HOME/lookaround.sh \$INPUT_TAR_DIR_LOCAL/a/f4
```
which launches 2 jobs checking for the file "f4" in the tarfile contents; the two job outputs end like:
```
File /cvmfs/fifeuser1.opensciencegrid.org/sw/fermilab/16cb76e2b4487fbc73d0ce00378078a90e9dbb3b2efc938ec61e9b9529cb8560/a/f4 not found, failing job..
Thu Jul 13 21:46:17 UTC 2023 lookaround.sh COMPLETED with exit status 1
```
```
Verified /cvmfs/fifeuser2.opensciencegrid.org/sw/fermilab/ad4812c5422adbe975af1f74e060623e1ea6a44100e312a866ac804b102ff800/a/f4 exists
=== out dirs: CONDOR_DIR_INPUT ===
CONDOR_DIR_INPUT = /srv/no_xfer/0/TRANSFERRED_INPUT_FILES
Thu Jul 13 21:52:15 UTC 2023 lookaround.sh COMPLETED with exit status 0
```

@kherner -- can you provide a specific tarball, or a specific directory to tar up and a file that you add, that causes this?  
Otherwise I'm going to close this as a cannot reproduce.

**Comment by marcmengel** [comment] 2023-10-03 18:33
Still cannot reproduce this bug.   Closing out ticket.

**Closed by marcmengel** 2023-10-03 18:33 UTC
Labels: bug
